#127: Prepared release 7.1.0
exasol/r-exasol pull request #128
Opened 2022-07-11 16:11 UTC by tomuben

2022-07-11 16:36 UTC, tkilias requested changes

2022-07-11 16:37 UTC, tomuben commented on README.md
> +The package gets tested in Github against 4.0 and 4.1 (and 3.x for Linux!). For R 3.6 and earlier, an older RODBC package is necessary, the newer versions (1.3-17 and upwards) only support R 4.0. You
Fixed

2022-07-11 16:48 UTC, tkilias approved these changes

2022-07-12 10:05 UTC, tkilias approved these changes

2022-07-12 10:06 UTC, merged